fullnameOverride: config-server

image:
  repository: k8s
  name: config-server
  pullPolicy: Never
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

ports:
  - name: http
    containerPort: 8888
    protocol: TCP

env:
  SPRING_PROFILES_ACTIVE: "docker,native"

livenessProbe_enabled: true
livenessProbe:
  httpGet:
    port: 8888
readinessProbe_enabled: true
readinessProbe:
  httpGet:
    port: 8888

service:
  ports:
    - port: 8888
      targetPort: http
      protocol: TCP
      name: http