# Default values for product-composite.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: k8s
  name: product-composite
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: product-composite

ports:
  - containerPort: 9090


service:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30443
      targetPort: 9090



